import type { Attraction } from "./types"

const VERIFIED_AT = "2026-07-15T00:00:00+08:00"
const SCORE_BASIS = "官方站热度排序快照、官方目的地级别与主题稀缺度的归一化派生值；非OTA评分"

type Seed = Omit<Attraction, "last_updated" | "score_basis" | "rating" | "review_count"> & {
  rating?: number | null
  review_count?: number | null
}

function pack(items: Seed[]): Attraction[] {
  return items.map(item => ({
    ...item,
    rating: item.rating ?? null,
    review_count: item.review_count ?? null,
    score_basis: SCORE_BASIS,
    last_updated: VERIFIED_AT,
  }))
}

const HOKKAIDO = pack([
  { id:"jp-hkd-lake-toya",country_code:"JPN",region_id:"hokkaido",name:"洞爷湖",name_en:"Lake Toya",lat_wgs84:42.603, lng_wgs84:140.852,category_l1:"自然风光",category_l2:"湖泊",popularity_score:99,niche_score:86,tags:["火山湖","亲子","温泉","自驾"],best_season:"全年",address:"北海道虻田郡洞爷湖町",price:"公共湖区免费，设施另计",opening_hours:"全年开放；设施时间以官方页面为准",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10050.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0050/10050_9_l.jpg" },
  { id:"jp-hkd-otaru-canal",country_code:"JPN",region_id:"hokkaido",name:"小樽运河",name_en:"Otaru Canal",lat_wgs84:43.198, lng_wgs84:140.994,category_l1:"人文历史",category_l2:"现代建筑",popularity_score:98,niche_score:78,tags:["历史街区","夜景","亲子"],best_season:"全年",address:"北海道小樽市港町",price:"公共步道免费",opening_hours:"全天开放",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10040.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0040/10040_1_l.jpg" },
  { id:"jp-hkd-blue-pond",country_code:"JPN",region_id:"hokkaido",name:"白金青池",name_en:"Shirogane Blue Pond",lat_wgs84:43.4935,lng_wgs84:142.614,category_l1:"网红奇观",category_l2:"季节限定",popularity_score:97,niche_score:83,tags:["摄影","蓝色湖面","美瑛"],best_season:"05—10月 / 冬季点灯",address:"北海道上川郡美瑛町白金",price:"免费",opening_hours:"季节开放时间以官方页面为准",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10511.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0511/10511_4_l.jpg" },
  { id:"jp-hkd-farm-tomita",country_code:"JPN",region_id:"hokkaido",name:"富田农场",name_en:"Farm Tomita",lat_wgs84:43.418,lng_wgs84:142.425,category_l1:"自然风光",category_l2:"草原",popularity_score:96,niche_score:76,tags:["薰衣草","花田","亲子"],best_season:"06—08月",address:"北海道空知郡中富良野町",price:"入园政策以官方页面为准",opening_hours:"随季节变化",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10174.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0174/10174_1_l.jpg" },
  { id:"jp-hkd-shiretoko-five-lakes",country_code:"JPN",region_id:"hokkaido",name:"知床五湖",name_en:"Shiretoko Five Lakes",lat_wgs84:44.125,lng_wgs84:145.079,category_l1:"户外极限",category_l2:"徒步",popularity_score:93,niche_score:98,tags:["世界自然遗产","原始森林","野生动物"],best_season:"04—11月",address:"北海道斜里郡斜里町远音别村",price:"步道制度与费用以官方页面为准",opening_hours:"季节开放",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10404.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0404/10404_7_l.jpg" },
  { id:"jp-hkd-asahidake",country_code:"JPN",region_id:"hokkaido",name:"旭岳缆车",name_en:"Daisetsuzan Asahidake Ropeway",lat_wgs84:43.649,lng_wgs84:142.791,category_l1:"户外极限",category_l2:"徒步",popularity_score:91,niche_score:97,tags:["大雪山","高山徒步","红叶"],best_season:"06—10月 / 冬季雪季",address:"北海道上川郡东川町旭岳温泉",price:"收费；以运营方公告为准",opening_hours:"随季节与天气变化",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10355.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0355/10355_1_l.jpg" },
  { id:"jp-hkd-jigokudani",country_code:"JPN",region_id:"hokkaido",name:"登别地狱谷",name_en:"Noboribetsu Jigokudani",lat_wgs84:42.497,lng_wgs84:141.144,category_l1:"自然风光",category_l2:"遗址",popularity_score:95,niche_score:88,tags:["火山地貌","温泉","栈道"],best_season:"全年",address:"北海道登别市登别温泉町",price:"景区免费；停车收费",opening_hours:"步道受天气影响",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10157.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0157/10157_5_l.jpg" },
  { id:"jp-hkd-hakodate",country_code:"JPN",region_id:"hokkaido",name:"函馆山",name_en:"Mount Hakodate",lat_wgs84:41.759,lng_wgs84:140.704,category_l1:"自然风光",category_l2:"雪山",popularity_score:94,niche_score:75,tags:["夜景","缆车","城市"],best_season:"全年",address:"北海道函馆市函馆山",price:"山体公共区域免费；交通另计",opening_hours:"交通管制随季节变化",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10095.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0095/10095_8_l.jpg" },
  { id:"jp-hkd-lake-shikotsu",country_code:"JPN",region_id:"hokkaido",name:"支笏湖",name_en:"Lake Shikotsu",lat_wgs84:42.759,lng_wgs84:141.329,category_l1:"自然风光",category_l2:"湖泊",popularity_score:92,niche_score:90,tags:["透明湖水","独木舟","温泉"],best_season:"全年",address:"北海道千岁市支笏湖温泉",price:"公共湖区免费",opening_hours:"全年开放；活动另计",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10145.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0145/10145_1_l.jpg" },
  { id:"jp-hkd-yotei",country_code:"JPN",region_id:"hokkaido",name:"羊蹄山",name_en:"Mount Yotei",lat_wgs84:42.826,lng_wgs84:140.811,category_l1:"户外极限",category_l2:"徒步",popularity_score:88,niche_score:96,tags:["火山","登山","摄影"],best_season:"06—10月",address:"北海道后志综合振兴局区域",price:"登山免费",opening_hours:"登山季与天气限制",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10334.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0334/10334_7_l.jpg" },
  { id:"jp-hkd-rusutsu",country_code:"JPN",region_id:"hokkaido",name:"留寿都度假村",name_en:"Rusutsu Resort",lat_wgs84:42.738,lng_wgs84:140.872,category_l1:"户外极限",category_l2:"滑雪",popularity_score:90,niche_score:94,tags:["滑雪","粉雪","亲子"],best_season:"12—04月",address:"北海道虻田郡留寿都村",price:"雪票与项目收费",opening_hours:"雪季与天气决定",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10331.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0331/10331_5_l.jpg" },
  { id:"jp-hkd-cape-kamui",country_code:"JPN",region_id:"hokkaido",name:"神威岬",name_en:"Cape Kamui",lat_wgs84:43.333,lng_wgs84:140.348,category_l1:"自然风光",category_l2:"海洋",popularity_score:89,niche_score:93,tags:["积丹蓝","海岸徒步","摄影"],best_season:"05—10月",address:"北海道积丹郡积丹町神岬町",price:"免费",opening_hours:"步道开放受天气影响",data_source:"Hokkaido Tourism Organization · HOKKAIDO LOVE!",source_url:"https://www.visit-hokkaido.jp/en/spot/detail_10342.html",image_url:"https://www.visit-hokkaido.jp/lsc/upfile/spot/0001/0342/10342_7_l.jpg" },
])

const WORLD = pack([
  // Japan — Kansai / Okinawa
  { id:"jp-ks-kinkakuji",country_code:"JPN",region_id:"kinki",name:"金阁寺",name_en:"Kinkaku-ji",lat_wgs84:35.0394,lng_wgs84:135.7292,category_l1:"人文历史",category_l2:"古寺",popularity_score:99,niche_score:70,tags:["京都","世界遗产","庭园"],best_season:"03—05月 / 11月",address:"京都府京都市北区",price:"入场收费",opening_hours:"以官方公告为准",data_source:"Japan National Tourism Organization",source_url:"https://www.japan.travel/en/spot/1231/",image_url:"https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=85" },
  { id:"jp-ks-nara-park",country_code:"JPN",region_id:"kinki",name:"奈良公园",name_en:"Nara Park",lat_wgs84:34.6851,lng_wgs84:135.8430,category_l1:"自然风光",category_l2:"城市公园",popularity_score:97,niche_score:74,tags:["鹿","亲子","古都"],best_season:"全年",address:"奈良县奈良市",price:"公园免费；部分寺院收费",opening_hours:"全天",data_source:"Japan National Tourism Organization",source_url:"https://www.japan.travel/en/destinations/kansai/nara/",image_url:"https://images.unsplash.com/photo-1528164344705-47542687000d?auto=format&fit=crop&w=900&q=85" },
  { id:"jp-ks-fushimi",country_code:"JPN",region_id:"kinki",name:"伏见稻荷大社",name_en:"Fushimi Inari Taisha",lat_wgs84:34.9671,lng_wgs84:135.7727,category_l1:"人文历史",category_l2:"神社",popularity_score:98,niche_score:72,tags:["千本鸟居","徒步","摄影"],best_season:"全年",address:"京都府京都市伏见区",price:"参拜免费",opening_hours:"全天",data_source:"Japan National Tourism Organization",source_url:"https://www.japan.travel/en/spot/1168/",image_url:"https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=900&q=85" },
  { id:"jp-ok-kerama",country_code:"JPN",region_id:"kyushu",name:"庆良间群岛",name_en:"Kerama Islands",lat_wgs84:26.199,lng_wgs84:127.333,category_l1:"自然风光",category_l2:"海洋",popularity_score:98,niche_score:91,tags:["潜水","白沙滩","离岛"],best_season:"04—10月",address:"冲绳县岛尻郡",price:"交通与活动另计",opening_hours:"船班随季节变化",data_source:"Okinawa Convention & Visitors Bureau",source_url:"https://www.visitokinawa.jp/",image_url:"https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=85" },
  { id:"jp-ok-aquarium",country_code:"JPN",region_id:"kyushu",name:"美丽海水族馆",name_en:"Churaumi Aquarium",lat_wgs84:26.694,lng_wgs84:127.878,category_l1:"超级工程",category_l2:"场馆",popularity_score:96,niche_score:68,tags:["亲子","鲸鲨","室内"],best_season:"全年",address:"冲绳县国头郡本部町",price:"收费",opening_hours:"以场馆公告为准",data_source:"Okinawa Churaumi Aquarium",source_url:"https://churaumi.okinawa/en/",image_url:"https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?auto=format&fit=crop&w=900&q=85" },

  // China
  { id:"cn-xj-kanas",country_code:"CHN",region_id:"northwest",name:"喀纳斯",name_en:"Kanas",lat_wgs84:48.704,lng_wgs84:87.018,category_l1:"自然风光",category_l2:"湖泊",popularity_score:99,niche_score:88,tags:["秋色","徒步","摄影"],best_season:"09—10月",address:"新疆阿勒泰地区布尔津县",price:"景区票务以当地公告为准",opening_hours:"季节开放",data_source:"新疆维吾尔自治区文化和旅游厅",source_url:"https://wlt.xinjiang.gov.cn/",image_url:"https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=85" },
  { id:"cn-xj-narat",country_code:"CHN",region_id:"northwest",name:"那拉提草原",name_en:"Narat Grassland",lat_wgs84:43.249,lng_wgs84:84.002,category_l1:"自然风光",category_l2:"草原",popularity_score:96,niche_score:90,tags:["骑马","花季","自驾"],best_season:"06—08月",address:"新疆伊犁哈萨克自治州新源县",price:"景区票务以当地公告为准",opening_hours:"季节开放",data_source:"新疆维吾尔自治区文化和旅游厅",source_url:"https://wlt.xinjiang.gov.cn/",image_url:"https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=85" },
  { id:"cn-xj-duku",country_code:"CHN",region_id:"northwest",name:"独库公路",name_en:"Duku Highway",lat_wgs84:43.0,lng_wgs84:84.5,category_l1:"户外极限",category_l2:"自驾",popularity_score:97,niche_score:94,tags:["史诗公路","峡谷","季节性"],best_season:"06—09月",address:"新疆独山子—库车",price:"公路通行；服务区另计",opening_hours:"冬季封闭，以路况公告为准",data_source:"新疆维吾尔自治区文化和旅游厅",source_url:"https://wlt.xinjiang.gov.cn/",image_url:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85" },
  { id:"cn-south-lijiang",country_code:"CHN",region_id:"south",name:"漓江",name_en:"Li River",lat_wgs84:25.201,lng_wgs84:110.424,category_l1:"自然风光",category_l2:"喀斯特",popularity_score:98,niche_score:80,tags:["游船","摄影","亲子"],best_season:"04—10月",address:"广西桂林—阳朔",price:"游船与景区收费",opening_hours:"以当地公告为准",data_source:"广西壮族自治区文化和旅游厅",source_url:"https://wlt.gxzf.gov.cn/",image_url:"https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=900&q=85" },

  // Europe
  { id:"is-south-skogafoss",country_code:"ISL",region_id:"south-iceland",name:"斯科加瀑布",name_en:"Skógafoss",lat_wgs84:63.532,lng_wgs84:-19.511,category_l1:"自然风光",category_l2:"瀑布",popularity_score:98,niche_score:82,tags:["南岸","自驾","摄影"],best_season:"全年",address:"South Iceland",price:"公共区域免费",opening_hours:"全天",data_source:"Visit Iceland",source_url:"https://www.visiticeland.com/",image_url:"https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=900&q=85" },
  { id:"is-south-jokulsarlon",country_code:"ISL",region_id:"south-iceland",name:"杰古沙龙冰河湖",name_en:"Jökulsárlón",lat_wgs84:64.048,lng_wgs84:-16.179,category_l1:"自然风光",category_l2:"冰川湖",popularity_score:99,niche_score:85,tags:["冰山","海豹","自驾"],best_season:"全年",address:"South-East Iceland",price:"公共观景点免费；游船另计",opening_hours:"季节活动另计",data_source:"Visit Iceland",source_url:"https://www.visiticeland.com/",image_url:"https://images.unsplash.com/photo-1531168556467-80aace0d0144?auto=format&fit=crop&w=900&q=85" },
  { id:"is-south-reynisfjara",country_code:"ISL",region_id:"south-iceland",name:"黑沙滩",name_en:"Reynisfjara",lat_wgs84:63.404,lng_wgs84:-19.066,category_l1:"自然风光",category_l2:"海岸",popularity_score:97,niche_score:80,tags:["玄武岩","浪危","摄影"],best_season:"全年",address:"Vík area",price:"免费",opening_hours:"注意安全警示",data_source:"SafeTravel Iceland",source_url:"https://safetravel.is/",image_url:"https://images.unsplash.com/photo-1476610182048-b716b8518aae?auto=format&fit=crop&w=900&q=85" },
  { id:"ch-bo-jungfrau",country_code:"CHE",region_id:"alpine-ch",name:"少女峰",name_en:"Jungfraujoch",lat_wgs84:46.547,lng_wgs84:7.980,category_l1:"超级工程",category_l2:"高山列车",popularity_score:99,niche_score:76,tags:["雪峰","观景","亲子"],best_season:"06—09月",address:"Bernese Oberland",price:"列车收费",opening_hours:"以 Jungfrau Railways 为准",data_source:"Switzerland Tourism",source_url:"https://www.myswitzerland.com/en/",image_url:"https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=900&q=85" },
  { id:"ch-bo-lauterbrunnen",country_code:"CHE",region_id:"alpine-ch",name:"劳特布龙嫩",name_en:"Lauterbrunnen",lat_wgs84:46.593,lng_wgs84:7.908,category_l1:"自然风光",category_l2:"山谷",popularity_score:96,niche_score:88,tags:["瀑布谷","徒步","摄影"],best_season:"05—10月",address:"Lauterbrunnen",price:"山谷免费；缆车另计",opening_hours:"全天",data_source:"Switzerland Tourism",source_url:"https://www.myswitzerland.com/en/",image_url:"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=900&q=85" },
  { id:"no-wf-preikestolen",country_code:"NOR",region_id:"west-no",name:"布道石",name_en:"Preikestolen",lat_wgs84:58.986,lng_wgs84:6.190,category_l1:"户外极限",category_l2:"徒步",popularity_score:98,niche_score:90,tags:["峡湾","悬崖","徒步"],best_season:"05—09月",address:"Rogaland",price:"停车收费",opening_hours:"步道受季节影响",data_source:"Visit Norway",source_url:"https://www.visitnorway.com/",image_url:"https://images.unsplash.com/photo-1507272931001-fc06c17e4f43?auto=format&fit=crop&w=900&q=85" },
  { id:"it-tuscany-siena",country_code:"ITA",region_id:"central-italy",name:"锡耶纳古城",name_en:"Siena",lat_wgs84:43.3188,lng_wgs84:11.3308,category_l1:"人文历史",category_l2:"古城",popularity_score:97,niche_score:84,tags:["世界遗产","广场","美食"],best_season:"04—10月",address:"Siena, Tuscany",price:"部分场馆收费",opening_hours:"以场馆公告为准",data_source:"Visit Tuscany",source_url:"https://www.visittuscany.com/en/",image_url:"https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=900&q=85" },
  { id:"it-tuscany-valdorcia",country_code:"ITA",region_id:"central-italy",name:"奥尔恰谷",name_en:"Val d'Orcia",lat_wgs84:43.05,lng_wgs84:11.62,category_l1:"自然风光",category_l2:"丘陵",popularity_score:95,niche_score:92,tags:["骑行","摄影","庄园"],best_season:"04—06 / 09—10月",address:"Val d'Orcia",price:"公共道路免费",opening_hours:"全天",data_source:"Visit Tuscany",source_url:"https://www.visittuscany.com/en/",image_url:"https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=900&q=85" },

  // Oceania
  { id:"nz-si-milford",country_code:"NZL",region_id:"south-island",name:"米尔福德峡湾",name_en:"Milford Sound",lat_wgs84:-44.671,lng_wgs84:167.925,category_l1:"自然风光",category_l2:"峡湾",popularity_score:99,niche_score:82,tags:["游船","瀑布","摄影"],best_season:"11—03月",address:"Fiordland National Park",price:"游船收费",opening_hours:"以运营商为准",data_source:"Tourism New Zealand",source_url:"https://www.newzealand.com/int/milford-sound/",image_url:"https://images.unsplash.com/photo-1469521669194-babb45599def?auto=format&fit=crop&w=900&q=85" },
  { id:"nz-si-queenstown",country_code:"NZL",region_id:"south-island",name:"皇后镇",name_en:"Queenstown",lat_wgs84:-45.031,lng_wgs84:168.662,category_l1:"户外极限",category_l2:"湖泊城镇",popularity_score:98,niche_score:75,tags:["亲子","跳伞","湖景"],best_season:"11—03月",address:"Queenstown",price:"城镇免费；活动另计",opening_hours:"全天",data_source:"Tourism New Zealand",source_url:"https://www.newzealand.com/int/queenstown/",image_url:"https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=900&q=85" },
  { id:"au-qld-gbr",country_code:"AUS",region_id:"qld",name:"大堡礁",name_en:"Great Barrier Reef",lat_wgs84:-18.287,lng_wgs84:147.699,category_l1:"自然风光",category_l2:"珊瑚礁",popularity_score:99,niche_score:80,tags:["潜水","浮潜","海岛"],best_season:"06—10月",address:"Queensland Marine Park",price:"出海与保护费另计",opening_hours:"船班随天气",data_source:"Great Barrier Reef Marine Park Authority",source_url:"https://www2.gbrmpa.gov.au/",image_url:"https://images.unsplash.com/photo-1587139223877-04cb899fa3e8?auto=format&fit=crop&w=900&q=85" },
  { id:"au-qld-daintree",country_code:"AUS",region_id:"qld",name:"丹翠雨林",name_en:"Daintree Rainforest",lat_wgs84:-16.17,lng_wgs84:145.418,category_l1:"自然风光",category_l2:"雨林",popularity_score:95,niche_score:91,tags:["世界遗产","徒步","亲子"],best_season:"05—09月",address:"Far North Queensland",price:"园区与渡轮另计",opening_hours:"以公园公告为准",data_source:"Tourism and Events Queensland",source_url:"https://www.queensland.com/",image_url:"https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=85" },
  { id:"id-bali-penida",country_code:"IDN",region_id:"bali-nt",name:"努沙佩尼达",name_en:"Nusa Penida",lat_wgs84:-8.727,lng_wgs84:115.544,category_l1:"自然风光",category_l2:"离岛",popularity_score:97,niche_score:89,tags:["悬崖","潜水","摄影"],best_season:"05—09月",address:"Nusa Penida, Bali",price:"船班与景点另计",opening_hours:"全天",data_source:"Wonderful Indonesia",source_url:"https://www.indonesia.travel/",image_url:"https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?auto=format&fit=crop&w=900&q=85" },
  { id:"id-bali-tegalalang",country_code:"IDN",region_id:"bali-nt",name:"德格拉朗梯田",name_en:"Tegalalang Rice Terrace",lat_wgs84:-8.431,lng_wgs84:115.279,category_l1:"人文历史",category_l2:"农业景观",popularity_score:94,niche_score:78,tags:["稻田","摄影","轻徒步"],best_season:"全年",address:"Ubud, Bali",price:"捐赠/入场视当地规定",opening_hours:"白天",data_source:"Wonderful Indonesia",source_url:"https://www.indonesia.travel/",image_url:"https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=900&q=85" },
  { id:"th-and-phi-phi",country_code:"THA",region_id:"south-th",name:"皮皮岛",name_en:"Phi Phi Islands",lat_wgs84:7.741,lng_wgs84:98.778,category_l1:"自然风光",category_l2:"海岛",popularity_score:98,niche_score:76,tags:["浮潜","海湾","亲子"],best_season:"11—04月",address:"Krabi",price:"船班与国家公园费另计",opening_hours:"船班季节性",data_source:"Tourism Authority of Thailand",source_url:"https://www.tourismthailand.org/",image_url:"https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?auto=format&fit=crop&w=900&q=85" },
  { id:"th-and-phangnga",country_code:"THA",region_id:"south-th",name:"攀牙湾",name_en:"Phang Nga Bay",lat_wgs84:8.274,lng_wgs84:98.501,category_l1:"自然风光",category_l2:"石灰岩海湾",popularity_score:96,niche_score:88,tags:["长尾船","洞穴","摄影"],best_season:"11—04月",address:"Phang Nga",price:"国家公园与船班另计",opening_hours:"白天",data_source:"Tourism Authority of Thailand",source_url:"https://www.tourismthailand.org/",image_url:"https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=900&q=85" },

  // North America
  { id:"us-wc-yosemite",country_code:"USA",region_id:"west",name:"优胜美地",name_en:"Yosemite National Park",lat_wgs84:37.8651,lng_wgs84:-119.5383,category_l1:"自然风光",category_l2:"国家公园",popularity_score:99,niche_score:78,tags:["瀑布","徒步","自驾"],best_season:"05—10月",address:"California",price:"公园入场费",opening_hours:"以 NPS 公告为准",data_source:"National Park Service",source_url:"https://www.nps.gov/yose/index.htm",image_url:"https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=900&q=85" },
  { id:"us-wc-big-sur",country_code:"USA",region_id:"west",name:"大苏尔海岸",name_en:"Big Sur",lat_wgs84:36.2704,lng_wgs84:-121.8081,category_l1:"自然风光",category_l2:"海岸公路",popularity_score:97,niche_score:86,tags:["一号公路","悬崖","摄影"],best_season:"03—06 / 09—11月",address:"California Highway 1",price:"公共观景点免费",opening_hours:"注意道路封闭",data_source:"Caltrans / Visit California",source_url:"https://www.visitcalifornia.com/",image_url:"https://images.unsplash.com/photo-1515894347712-4d9164b20c6c?auto=format&fit=crop&w=900&q=85" },
  { id:"us-rock-yellowstone",country_code:"USA",region_id:"mountain-us",name:"黄石公园",name_en:"Yellowstone",lat_wgs84:44.4280,lng_wgs84:-110.5885,category_l1:"自然风光",category_l2:"国家公园",popularity_score:99,niche_score:80,tags:["间歇泉","野生动物","露营"],best_season:"05—09月",address:"Wyoming / Montana / Idaho",price:"公园入场费",opening_hours:"以 NPS 公告为准",data_source:"National Park Service",source_url:"https://www.nps.gov/yell/index.htm",image_url:"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=900&q=85" },
  { id:"ca-rock-louise",country_code:"CAN",region_id:"west-ca",name:"露易丝湖",name_en:"Lake Louise",lat_wgs84:51.4254,lng_wgs84:-116.1773,category_l1:"自然风光",category_l2:"冰川湖",popularity_score:99,niche_score:77,tags:["班夫","摄影","徒步"],best_season:"06—09月",address:"Banff National Park",price:"国家公园通行证",opening_hours:"全天；停车预约季节性",data_source:"Parks Canada",source_url:"https://parks.canada.ca/pn-np/ab/banff",image_url:"https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&w=900&q=85" },
  { id:"ca-rock-moraine",country_code:"CAN",region_id:"west-ca",name:"梦莲湖",name_en:"Moraine Lake",lat_wgs84:51.3217,lng_wgs84:-116.1860,category_l1:"自然风光",category_l2:"冰川湖",popularity_score:98,niche_score:84,tags:["十峰谷","摄影","班车"],best_season:"06—09月",address:"Banff National Park",price:"国家公园通行证",opening_hours:"旺季限制私家车",data_source:"Parks Canada",source_url:"https://parks.canada.ca/pn-np/ab/banff",image_url:"https://images.unsplash.com/photo-1565019011521-b0575cbb57c9?auto=format&fit=crop&w=900&q=85" },
  { id:"ca-rock-icefields",country_code:"CAN",region_id:"west-ca",name:"冰原大道",name_en:"Icefields Parkway",lat_wgs84:52.219,lng_wgs84:-117.224,category_l1:"户外极限",category_l2:"自驾",popularity_score:97,niche_score:90,tags:["公路","冰川","观景台"],best_season:"06—09月",address:"Banff—Jasper",price:"国家公园通行证",opening_hours:"冬季路况限制",data_source:"Parks Canada",source_url:"https://parks.canada.ca/pn-np/ab/jasper",image_url:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85" },

  // South America
  { id:"br-rio-sugarloaf",country_code:"BRA",region_id:"southeast-br",name:"糖面包山",name_en:"Sugarloaf Mountain",lat_wgs84:-22.9492,lng_wgs84:-43.1545,category_l1:"自然风光",category_l2:"海岸山体",popularity_score:98,niche_score:76,tags:["缆车","海湾","城市"],best_season:"05—09月",address:"Rio de Janeiro",price:"缆车收费",opening_hours:"以运营商为准",data_source:"Embratur / Visit Brasil",source_url:"https://www.visitbrasil.com/",image_url:"https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=900&q=85" },
  { id:"br-rio-christ",country_code:"BRA",region_id:"southeast-br",name:"基督像",name_en:"Christ the Redeemer",lat_wgs84:-22.9519,lng_wgs84:-43.2105,category_l1:"人文历史",category_l2:"地标",popularity_score:99,niche_score:68,tags:["观景","亲子","世界遗产"],best_season:"05—09月",address:"Corcovado, Rio",price:"火车/厢式车收费",opening_hours:"以官方公告为准",data_source:"Embratur / Visit Brasil",source_url:"https://www.visitbrasil.com/",image_url:"https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?auto=format&fit=crop&w=900&q=85" },
  { id:"br-iguazu-falls",country_code:"BRA",region_id:"iguazu",name:"伊瓜苏瀑布",name_en:"Iguaçu Falls",lat_wgs84:-25.6953,lng_wgs84:-54.4367,category_l1:"自然风光",category_l2:"瀑布",popularity_score:99,niche_score:82,tags:["国家公园","摄影","亲子"],best_season:"03—11月",address:"Foz do Iguaçu",price:"国家公园门票",opening_hours:"以公园公告为准",data_source:"ICMBio / Visit Brasil",source_url:"https://www.visitbrasil.com/",image_url:"https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=900&q=85" },
  { id:"ar-pat-perito",country_code:"ARG",region_id:"patagonia-ar",name:"佩里托莫雷诺冰川",name_en:"Perito Moreno Glacier",lat_wgs84:-50.4967,lng_wgs84:-73.1377,category_l1:"自然风光",category_l2:"冰川",popularity_score:99,niche_score:88,tags:["巴塔哥尼亚","观景栈道","摄影"],best_season:"11—03月",address:"Los Glaciares NP",price:"国家公园门票",opening_hours:"以公园公告为准",data_source:"Argentina Tourism / Parques Nacionales",source_url:"https://www.argentina.travel/",image_url:"https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?auto=format&fit=crop&w=900&q=85" },
  { id:"ar-pat-fitzroy",country_code:"ARG",region_id:"patagonia-ar",name:"菲茨罗伊峰",name_en:"Mount Fitz Roy",lat_wgs84:-49.2713,lng_wgs84:-73.0432,category_l1:"户外极限",category_l2:"徒步",popularity_score:97,niche_score:95,tags:["艾尔查尔腾","高山湖","徒步"],best_season:"11—03月",address:"El Chaltén",price:"公共步道为主",opening_hours:"全天；天气限制",data_source:"Argentina Tourism",source_url:"https://www.argentina.travel/",image_url:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85" },
  { id:"pe-cusco-machu",country_code:"PER",region_id:"sierra-pe",name:"马丘比丘",name_en:"Machu Picchu",lat_wgs84:-13.1631,lng_wgs84:-72.5450,category_l1:"人文历史",category_l2:"遗址",popularity_score:99,niche_score:72,tags:["世界遗产","高原","预约"],best_season:"05—09月",address:"Cusco Region",price:"门票需预约",opening_hours:"以官方票务为准",data_source:"PROMPERÚ / Ministerio de Cultura",source_url:"https://www.peru.travel/en",image_url:"https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=900&q=85" },
  { id:"pe-cusco-valley",country_code:"PER",region_id:"sierra-pe",name:"圣谷",name_en:"Sacred Valley",lat_wgs84:-13.3167,lng_wgs84:-72.0833,category_l1:"人文历史",category_l2:"河谷遗址",popularity_score:95,niche_score:86,tags:["印加","市场","亲子"],best_season:"05—09月",address:"Urubamba Valley",price:"部分遗址收费",opening_hours:"以当地公告为准",data_source:"PROMPERÚ",source_url:"https://www.peru.travel/en",image_url:"https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=900&q=85" },
  { id:"cl-pat-torres",country_code:"CHL",region_id:"patagonia-cl",name:"托雷斯德尔帕伊内",name_en:"Torres del Paine",lat_wgs84:-50.9423,lng_wgs84:-73.4068,category_l1:"户外极限",category_l2:"国家公园",popularity_score:99,niche_score:90,tags:["W线","摄影","露营"],best_season:"11—03月",address:"Magallanes, Chile",price:"国家公园门票",opening_hours:"以 CONAF 为准",data_source:"Chile Travel / CONAF",source_url:"https://chile.travel/en",image_url:"https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=900&q=85" },
  { id:"cl-atacama-valle",country_code:"CHL",region_id:"atacama",name:"月亮谷",name_en:"Valle de la Luna",lat_wgs84:-22.9270,lng_wgs84:-68.3222,category_l1:"自然风光",category_l2:"沙漠",popularity_score:96,niche_score:91,tags:["日落","摄影","高海拔"],best_season:"全年（避盛夏正午）",address:"San Pedro de Atacama",price:"保护区门票",opening_hours:"以公园公告为准",data_source:"Chile Travel",source_url:"https://chile.travel/en",image_url:"https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=900&q=85" },

  // Africa
  { id:"za-cape-point",country_code:"ZAF",region_id:"cape-region",name:"好望角",name_en:"Cape Point",lat_wgs84:-34.3568,lng_wgs84:18.4977,category_l1:"自然风光",category_l2:"海岸",popularity_score:98,niche_score:80,tags:["自驾","灯塔","保护区"],best_season:"09—04月",address:"Table Mountain National Park",price:"公园门票",opening_hours:"以 SANParks 为准",data_source:"South African Tourism / SANParks",source_url:"https://www.southafrica.net/",image_url:"https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=900&q=85" },
  { id:"za-cape-table",country_code:"ZAF",region_id:"cape-region",name:"桌山",name_en:"Table Mountain",lat_wgs84:-33.9628,lng_wgs84:18.4098,category_l1:"自然风光",category_l2:"山体",popularity_score:99,niche_score:74,tags:["缆车","徒步","城市"],best_season:"全年（避强风日）",address:"Cape Town",price:"缆车收费",opening_hours:"受风关闭",data_source:"South African Tourism",source_url:"https://www.southafrica.net/",image_url:"https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=900&q=85" },
  { id:"za-kruger",country_code:"ZAF",region_id:"kruger",name:"克鲁格国家公园",name_en:"Kruger National Park",lat_wgs84:-24.0,lng_wgs84:31.5,category_l1:"自然风光",category_l2:"野生动物",popularity_score:99,niche_score:85,tags:["自驾观兽","摄影","亲子"],best_season:"05—09月",address:"Mpumalanga / Limpopo",price:"公园门票",opening_hours:"以 SANParks 为准",data_source:"SANParks",source_url:"https://www.sanparks.org/parks/kruger",image_url:"https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=900&q=85" },
  { id:"eg-giza-pyramids",country_code:"EGY",region_id:"cairo-giza",name:"吉萨金字塔",name_en:"Giza Pyramids",lat_wgs84:29.9792,lng_wgs84:31.1342,category_l1:"人文历史",category_l2:"遗址",popularity_score:99,niche_score:70,tags:["世界遗产","亲子","摄影"],best_season:"10—03月",address:"Giza",price:"门票与可选区域另计",opening_hours:"以官方公告为准",data_source:"Egypt Tourism / Ministry of Tourism",source_url:"https://egypt.travel/",image_url:"https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=900&q=85" },
  { id:"eg-luxor-karnak",country_code:"EGY",region_id:"luxor-nile",name:"卡尔纳克神庙",name_en:"Karnak Temple",lat_wgs84:25.7188,lng_wgs84:32.6573,category_l1:"人文历史",category_l2:"神庙",popularity_score:97,niche_score:82,tags:["尼罗河","考古","夜灯"],best_season:"10—03月",address:"Luxor",price:"门票收费",opening_hours:"以官方公告为准",data_source:"Egypt Tourism",source_url:"https://egypt.travel/",image_url:"https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=85" },
  { id:"eg-redsea-hurghada",country_code:"EGY",region_id:"red-sea",name:"赫尔格达珊瑚礁",name_en:"Hurghada Reefs",lat_wgs84:27.2579,lng_wgs84:33.8116,category_l1:"自然风光",category_l2:"潜水",popularity_score:95,niche_score:88,tags:["浮潜","亲子","度假"],best_season:"全年",address:"Red Sea",price:"出海活动另计",opening_hours:"船班随天气",data_source:"Egypt Tourism",source_url:"https://egypt.travel/",image_url:"https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=85" },
  { id:"ma-marrakech-medina",country_code:"MAR",region_id:"marrakech-atlas",name:"马拉喀什老城",name_en:"Marrakech Medina",lat_wgs84:31.6295,lng_wgs84:-7.9811,category_l1:"人文历史",category_l2:"古城",popularity_score:98,niche_score:78,tags:["集市","世界遗产","美食"],best_season:"03—05 / 09—11月",address:"Marrakech",price:"街区免费；场馆另计",opening_hours:"全天",data_source:"Morocco National Tourist Office",source_url:"https://www.visitmorocco.com/en",image_url:"https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?auto=format&fit=crop&w=900&q=85" },
  { id:"ma-atlas-imi",country_code:"MAR",region_id:"marrakech-atlas",name:"阿特拉斯山谷",name_en:"High Atlas Valleys",lat_wgs84:31.2,lng_wgs84:-7.9,category_l1:"户外极限",category_l2:"徒步",popularity_score:93,niche_score:94,tags:["村落","徒步","摄影"],best_season:"03—05 / 09—11月",address:"High Atlas",price:"向导可选",opening_hours:"白天",data_source:"Morocco National Tourist Office",source_url:"https://www.visitmorocco.com/en",image_url:"https://images.unsplash.com/photo-1539020140153-e479b8c22e70?auto=format&fit=crop&w=900&q=85" },
  { id:"ke-mara",country_code:"KEN",region_id:"masai-mara",name:"马赛马拉国家保护区",name_en:"Masai Mara",lat_wgs84:-1.4061,lng_wgs84:35.0117,category_l1:"自然风光",category_l2:"野生动物",popularity_score:99,niche_score:86,tags:["大迁徙","摄影","草原"],best_season:"07—10月",address:"Narok County",price:"保护区门票",opening_hours:"以保护区公告为准",data_source:"Kenya Tourism Board",source_url:"https://magicalkenya.com/",image_url:"https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=900&q=85" },
  { id:"tz-serengeti",country_code:"TZA",region_id:"serengeti",name:"塞伦盖蒂国家公园",name_en:"Serengeti National Park",lat_wgs84:-2.3333,lng_wgs84:34.8333,category_l1:"自然风光",category_l2:"野生动物",popularity_score:99,niche_score:87,tags:["迁徙","摄影","露营"],best_season:"06—10月",address:"Northern Circuit",price:"国家公园门票",opening_hours:"以 TANAPA 为准",data_source:"Tanzania Tourist Board",source_url:"https://www.tanzaniatourism.go.tz/",image_url:"https://images.unsplash.com/photo-1547970810-dc1eac37d174?auto=format&fit=crop&w=900&q=85" },
  { id:"tz-kilimanjaro",country_code:"TZA",region_id:"kilimanjaro",name:"乞力马扎罗国家公园",name_en:"Kilimanjaro National Park",lat_wgs84:-3.0674,lng_wgs84:37.3556,category_l1:"户外极限",category_l2:"高山徒步",popularity_score:98,niche_score:93,tags:["非洲屋脊","多日徒步","营地"],best_season:"01—03 / 06—10月",address:"Kilimanjaro Region",price:"公园与向导费用",opening_hours:"需许可与向导",data_source:"Tanzania National Parks",source_url:"https://www.tanzaniaparks.go.tz/",image_url:"https://images.unsplash.com/photo-1609198092458-38a293c7ac4b?auto=format&fit=crop&w=900&q=85" },
  { id:"tz-zanzibar-stone",country_code:"TZA",region_id:"zanzibar",name:"桑给巴尔石头城",name_en:"Stone Town",lat_wgs84:-6.1630,lng_wgs84:39.1880,category_l1:"人文历史",category_l2:"古城",popularity_score:94,niche_score:85,tags:["世界遗产","香料","海岸"],best_season:"06—10月",address:"Zanzibar City",price:"街区免费；博物馆另计",opening_hours:"全天",data_source:"Tanzania Tourist Board",source_url:"https://www.tanzaniatourism.go.tz/",image_url:"https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=85" },
])

export const OFFICIAL_ATTRACTIONS: Attraction[] = [...HOKKAIDO, ...WORLD]

export function getOfficialAttractions(countryCode?: string, regionId?: string) {
  return OFFICIAL_ATTRACTIONS.filter(item =>
    (!countryCode || item.country_code === countryCode) &&
    (!regionId || item.region_id === regionId),
  )
}
